openapi: 3.0.3
components:
  schemas:
      User:
        properties:
          username:
            description: unique username
            type: string
          email:
            description: email address
            type: string
          phone:
            description: phone number
            type: number
          password:
            description: password
            type: string
          first_name:
            description: first name
            type: string
          last_name:
            description: last name
            type: string
          status:
            description: user status
            type: string
            enum:
              - ACTIVE
              - INACTIVE
              - BANNED
          role:
            description: user role
            type: string
            enum:
              - ADMIN
              - USER
          profile_picture:
            description: profile picture
            type: string
        required:
          - username
          - email
          - password
          - first_name

      Insight:
        properties:
          title:
            description: title of the insight
            type: string
          description:
            description: description of the insight
            type: string
          longitude:
            description: longitude of the insight
            type: number
          latitude:
            description: latitude of the insight
            type: number
          image:
            description: image of the insight
            type: string
          address:
            description: address of the insight
            type: string
          category:
            description: category of the insight
            type: string
          subcategory:
            description: subcategory of the insight
            type: string
          external_link:
            description: external link of the insight
            type: string
        required:
          - title
          - longitude
          - latitude

      Feedback:
        properties:
          rating:
            description: rating of the feedback
            type: number
          comment:
            description: comment of the feedback
            type: string
  parameters:
    user:
      name: user
      in: path
      description: Name or email of the user
      required: true
      schema:
        type: string
    insight:
        name: insight
        in: path
        description: ID of the insight
        required: true
        schema:
            type: string
    feedback:
        name: feedback
        in: path
        description: ID of the feedback
        required: true
        schema:
            type: string
  securitySchemes:
    localInsightsApiKey:
      type: apiKey
      name: Geodata-Api-Key
      in: header
info:
  title: Crowd Sourced Local Insights API
  version: 0.0.1
  description: API for the Crowd Sourced Local Insights project
  termsOfService: http://totally.not.placehold.er/
  contact:
    url: http://totally.not.placehold.er/
    email: webMasters@gmail.com
    name: Web Masters
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html


